version: 2.1 # use CircleCI 2.1
executors:
  go-container:
    docker:
      - image: circleci/golang:1.15.0
  go-lint:
    docker:
      - image: golangci/golangci-lint:v1.28.1-alpine
    resource_class: small
  circle-machine:
    machine:
      image: ubuntu-1604:202004-01
      #docker_layer_caching: true

orbs:
  checkmarx: checkmarx/circleci-kpi-shipper@0.11.0
  
jobs:
  docker-build:
    executor: docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - deploy:
          name: Docker Build
          command: |
            VERSION=2.0.0_RC2-TEST
            SHA1_SHORT=${CIRCLE_SHA1::7}
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} docker.io
            docker build --target java8 \
              -t ${DOCKER_REPO}:${SHA1_SHORT} \
              -t ${DOCKER_REPO}:${VERSION}-8 \
              -t ${DOCKER_REPO}:${VERSION} \
              -t ${DOCKER_REPO} \
              .
            docker build --target java11 \
              -t ${DOCKER_REPO}:${VERSION}-11 \
              .
            docker push ${DOCKER_REPO}:${SHA1_SHORT}
workflows:
  Visibility-workflow:
    jobs:
      - checkmarx/circleci-kpi-shipper
  Test-workflow:
    jobs:
      - docker-build:
          filters:
            branches: master
              ignore:
