name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@master #Github Action version
        with:
          project_name: astcli9
          base_uri: http://demo.ast-cloud.com
          client_id: ${{ secrets.CLIENT_ID }}
          secret: ${{ secrets.SECRET }}
          project_type: sast
          additional_params: --incremental false --preset-name "Checkmarx Default" --agent "GitHub Action"
          filter: "!*.zip"

      - uses: actions/upload-artifact@v2
        with:
          name: zip-file-download
          path: ./cx.zip
